baseURL = "https://wiki.cs61a.org/"
languageCode = "en-us"
title = "CS 61A Infra Wiki"

theme = "cs61a"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "wiki"
orderSectionsBy = "title"
