"""Add ChatMessage description

Revision ID: 00aea7233ef8
Revises: 5c55d6d588c5
Create Date: 2020-09-06 04:35:59.664574

"""

# revision identifiers, used by Alembic.
revision = "00aea7233ef8"
down_revision = "5c55d6d588c5"

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message", sa.Column("body", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "config_entries", "key", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "config_entries", "key", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.drop_column("chat_message", "body")
    # ### end Alembic commands ###
