"""support-default-ticket-description

Revision ID: 11e366ca2e4f
Revises: 680b44ae9515
Create Date: 2021-02-13 05:20:07.890020

"""

# revision identifiers, used by Alembic.
revision = "11e366ca2e4f"
down_revision = "680b44ae9515"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="default_description",
                value="",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
