"""Add chatmessage table

Revision ID: 5c55d6d588c5
Revises: 951e6bbdffc9
Create Date: 2020-09-06 04:26:45.280552

"""

# revision identifiers, used by Alembic.
revision = "5c55d6d588c5"
down_revision = "951e6bbdffc9"

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("course", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointment.id"]),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"]),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_message_appointment_id"),
        "chat_message",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_course"), "chat_message", ["course"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_group_id"), "chat_message", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_ticket_id"), "chat_message", ["ticket_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_user_id"), "chat_message", ["user_id"], unique=False
    )
    op.alter_column(
        "config_entries", "key", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "config_entries", "key", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.drop_index(op.f("ix_chat_message_user_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_ticket_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_group_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_course"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_appointment_id"), table_name="chat_message")
    op.drop_table("chat_message")
    # ### end Alembic commands ###
