"""add user heartbeat column

Revision ID: 951e6bbdffc9
Revises: 4c81c3744bc4
Create Date: 2020-09-06 04:04:50.903594

"""

# revision identifiers, used by Alembic.
revision = "951e6bbdffc9"
down_revision = "a870d3c6be98"

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("heartbeat_time", sa.DateTime(), nullable=True, index=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "heartbeat_reply")
    # ### end Alembic commands ###
