"""Add notification state

Revision ID: ab9f3b203744
Revises: 00aea7233ef8
Create Date: 2020-09-09 17:49:06.161756

"""

# revision identifiers, used by Alembic.
revision = "ab9f3b203744"
down_revision = "00aea7233ef8"

from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_queue_ping", sa.DateTime(), nullable=False),
        sa.Column("last_appointment_notif", sa.DateTime(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("course", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_state_course"),
        "notification_state",
        ["course"],
        unique=False,
    )
    op.add_column(
        "appointment", sa.Column("num_reminders_sent", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "num_reminders_sent")
    op.drop_index(op.f("ix_notification_state_course"), table_name="notification_state")
    op.drop_table("notification_state")
    # ### end Alembic commands ###
