"""support configurable party mode names

Revision ID: c2365b4ad424
Revises: f427b9253aff
Create Date: 2021-01-13 05:57:35.023733

"""

# revision identifiers, used by Alembic.
revision = "c2365b4ad424"
down_revision = "f427b9253aff"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="party_name",
                value="Party",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
