"""Add config to restrict to registered students only

Revision ID: f427b9253aff
Revises: 118cb294518a
Create Date: 2020-12-21 19:02:58.286415

"""

# revision identifiers, used by Alembic.
revision = "f427b9253aff"
down_revision = "118cb294518a"

from sqlalchemy import orm
from alembic import op
import sqlalchemy as sa
import oh_queue.models
from oh_queue.models import *


def upgrade():
    # Get alembic DB bind
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    for course in session.query(ConfigEntry.course).distinct():
        session.add(
            ConfigEntry(
                key="only_registered_students",
                value="false",
                public=True,
                course=course[0],
            )
        )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
