from typing import NamedTuple


class StaffMember(NamedTuple):
    firstName: str
    lastName: str
    emoji: str


STAFF = [
    StaffMember("Aaron", "Chen", ":aaron:"),
    StaffMember("Abhinav", "Ashar", ":abhinav:"),
    StaffMember("Addison", "Chan", ":addison:"),
    StaffMember("Albert", "Xu", ":albert:"),
    StaffMember("Alex", "Kassil", ":alex:"),
    StaffMember("Alicia", "Wang", ":alicia:"),
    StaffMember("Alina", "Herri", ":alina:"),
    StaffMember("Amrita", "Palaparthi", ":amrita:"),
    StaffMember("Andrew", "Lenz", ":andrew-l:"),
    StaffMember("Andrew", "Shieh", ":andrew-s:"),
    StaffMember("Animesh", "Agrawal", ":animesh:"),
    StaffMember("Arushi", "Somani", ":arushi:"),
    StaffMember("Ben", "Cuan", ":ben:"),
    StaffMember("Brandon", "Choy", ":brandon-c:"),
    StaffMember("Brandon", "Shin", ":brandon-s:"),
    StaffMember("Catherine", "Gee", ":catherine:"),
    StaffMember("Cesar", "Plascencia Zuniga", ":cesar:"),
    StaffMember("Chi", "Tsai", ":chi:"),
    StaffMember("Christine", "Luo", ":christine:"),
    StaffMember("Christopher", "Wang", ":christopher:"),
    StaffMember("Connie", "Shi", ":connie:"),
    StaffMember("Cooper", "Bedin", ":cooper:"),
    StaffMember("Crystal", "Wang", ":crystal:"),
    StaffMember("Daniel", "Shin", ":daniel:"),
    StaffMember("Derek", "Wan", ":derek:"),
    StaffMember("Eknoor", "Kaur", ":eknoor:"),
    StaffMember("Eric", "Wang", ":eric:"),
    StaffMember("Ethan", "Chiu", ":ethan:"),
    StaffMember("George", "Gikas", ":george:"),
    StaffMember("Griffin", "Prechter", ":griffin:"),
    StaffMember("Gurkaran", "S Goindi", ":gurkaran:"),
    StaffMember("Han", "Qi", ":han:"),
    StaffMember("Imran", "Khaliq", ":imran:"),
    StaffMember("Jade", "Singh", ":jade:"),
    StaffMember("Jamie", "Hong", ":jamie:"),
    StaffMember("Jemmy", "Zhou", ":jemmy:"),
    StaffMember("Jennifer", "Huang", ":jennifer:"),
    StaffMember("Jenny", "Wang", ":jenny:"),
    StaffMember("Jessica", "Yu", ":jessica:"),
    StaffMember("John", "So", ":john:"),
    StaffMember("Joshua", "Baum", ":joshua:"),
    StaffMember("Julie", "Ma", ":julie:"),
    StaffMember("Kaavya", "Shah", ":kaavya:"),
    StaffMember("Kenneth", "Chi", ":kenneth:"),
    StaffMember("Kevin", "Yang", ":kevin-y:"),
    StaffMember("Kevin", "Zhu", ":kevin-z:"),
    StaffMember("Khushi", "Malde", ":khushi:"),
    StaffMember("Kristy", "Lee", ":kristy:"),
    StaffMember("Laryn", "Qi", ":laryn:"),
    StaffMember("Lauren", "Meier", ":lauren:"),
    StaffMember("Linh", "Tran", ":linh:"),
    StaffMember("Lucy", "Wan", ":lucy:"),
    StaffMember("Mathilde", "Mckeever", ":mathilde:"),
    StaffMember("Megan", "Zhu", ":megan:"),
    StaffMember("Melanie", "Cooray", ":melanie:"),
    StaffMember("Melvin", "Aristio", ":melvin:"),
    StaffMember("Minnie", "Chen", ":minnie:"),
    StaffMember("Mohsin", "Sarwari", ":mohsin:"),
    StaffMember("Nancy", "Shaw", ":nancy:"),
    StaffMember("Nikhita", "Anumukonda", ":nikhita:"),
    StaffMember("Olivia", "Shiah", ":olivia:"),
    StaffMember("Owen", "Gong", ":owen:"),
    StaffMember("Parth", "Gupta", ":parth:"),
    StaffMember("Patricia", "Ouyang", ":patricia:"),
    StaffMember("Pranad", "Reddy", ":pranad:"),
    StaffMember("Rahul", "Arya", ":rahul-a:"),
    StaffMember("Rahul", "Devarapalli", ":rahul-d:"),
    StaffMember("Richard", "Roggenkemper", ":richard-r:"),
    StaffMember("Richard", "Zhu", ":richard-z:"),
    StaffMember("Rohan", "Dsouza", ":rohan:"),
    StaffMember("Sahil", "Morchi", ":sahil:"),
    StaffMember("Sameer", "Saptarshi", ":sameer:"),
    StaffMember("Samuel", "Taplin", ":samuel:"),
    StaffMember("Sarina", "Sabouri", ":sarina:"),
    StaffMember("Sean", "Obrien", ":sean-o:"),
    StaffMember("Sean", "Sananikone", ":sean-s:"),
    StaffMember("Selina", "Wu", ":selina:"),
    StaffMember("Shayna", "Kothari", ":shayna:"),
    StaffMember("Sherry", "Fan", ":sherry:"),
    StaffMember("Sophia", "Xiao", ":sophia:"),
    StaffMember("Sreevidya", "Ganga", ":sreevidya:"),
    StaffMember("Steven", "Chen", ":steven:"),
    StaffMember("Tim", "Tu", ":tim:"),
    StaffMember("Todd", "Yu", ":todd:"),
    StaffMember("Vanshaj", "Singhania", ":vanshaj:"),
    StaffMember("Vivian", "Lu", ":vivian:"),
    StaffMember("Yersultan", "Sapar", ":yersultan:"),
    StaffMember("John", "Denero", ":john:"),
    StaffMember("DeNero", "Denero", ":john:"),
]

STAFF_EMOJI = {x.emoji for x in STAFF}
