from typing import NamedTuple


class StaffMember(NamedTuple):
    firstName: str
    lastName: str
    emoji: str


STAFF=[
	StaffMember(firstName='Aaron', lastName='Chen', emoji=':aaron:'),
	StaffMember(firstName='Abhinav', lastName='Ashar', emoji=':abhinav:'),
	StaffMember(firstName='Addison', lastName='Chan', emoji=':addison:'),
	StaffMember(firstName='Albert', lastName='Xu', emoji=':albert:'),
	StaffMember(firstName='Alex', lastName='Kassil', emoji=':alex:'),
	StaffMember(firstName='Alicia', lastName='Wang', emoji=':alicia:'),
	StaffMember(firstName='Alina', lastName='Herri', emoji=':alina:'),
	StaffMember(firstName='Amit', lastName='Bhat', emoji=':amit:'),
	StaffMember(firstName='Amrita', lastName='Palaparthi', emoji=':amrita:'),
	StaffMember(firstName='Amritansh', lastName='Saraf', emoji=':amritansh:'),
	StaffMember(firstName='Andrew', lastName='Lenz', emoji=':andrew-l:'),
	StaffMember(firstName='Andrew', lastName='Shieh', emoji=':andrew-s:'),
	StaffMember(firstName='Andrew', lastName='Mcguire', emoji=':andrew-m:'),
	StaffMember(firstName='Animesh', lastName='Agrawal', emoji=':animesh:'),
	StaffMember(firstName='Arushi', lastName='Somani', emoji=':arushi:'),
	StaffMember(firstName='Ben', lastName='Cuan', emoji=':ben:'),
	StaffMember(firstName='Brandon', lastName='Choy', emoji=':brandon-c:'),
	StaffMember(firstName='Brandon', lastName='Shin', emoji=':brandon-s:'),
	StaffMember(firstName='Cait', lastName='Phan', emoji=':cait:'),
	StaffMember(firstName='Catherine', lastName='Gee', emoji=':catherine:'),
	StaffMember(firstName='Cesar', lastName='Plascencia Zuniga', emoji=':cesar:'),
	StaffMember(firstName='Chi', lastName='Tsai', emoji=':chi:'),
	StaffMember(firstName='Christine', lastName='Luo', emoji=':christine:'),
	StaffMember(firstName='Christopher', lastName='Wang', emoji=':christopher:'),
	StaffMember(firstName='Connie', lastName='Shi', emoji=':connie:'),
	StaffMember(firstName='Cooper', lastName='Bedin', emoji=':cooper:'),
	StaffMember(firstName='Crystal', lastName='Wang', emoji=':crystal:'),
	StaffMember(firstName='Cyrus', lastName='Bugwadia', emoji=':cyrus:'),
	StaffMember(firstName='Daniel', lastName='Shin', emoji=':daniel:'),
	StaffMember(firstName='Daphne', lastName='Pan', emoji=':daphne:'),
	StaffMember(firstName='DeNero', lastName='Denero', emoji=':john:'),
	StaffMember(firstName='Derek', lastName='Wan', emoji=':derek:'),
	StaffMember(firstName='Eknoor', lastName='Kaur', emoji=':eknoor:'),
	StaffMember(firstName='Emma', lastName='Yokota', emoji=':emma:'),
	StaffMember(firstName='Eric', lastName='Wang', emoji=':eric:'),
	StaffMember(firstName='Ethan', lastName='Chiu', emoji=':ethan:'),
	StaffMember(firstName='George', lastName='Gikas', emoji=':george:'),
	StaffMember(firstName='Griffin', lastName='Prechter', emoji=':griffin:'),
	StaffMember(firstName='Gurkaran', lastName='S Goindi', emoji=':gurkaran:'),
	StaffMember(firstName='Han', lastName='Qi', emoji=':han:'),
	StaffMember(firstName='Imran', lastName='Khaliq', emoji=':imran:'),
	StaffMember(firstName='Jade', lastName='Singh', emoji=':jade:'),
	StaffMember(firstName='Jamie', lastName='Hong', emoji=':jamie:'),
	StaffMember(firstName='Jemmy', lastName='Zhou', emoji=':jemmy:'),
	StaffMember(firstName='Jennifer', lastName='Huang', emoji=':jennifer:'),
	StaffMember(firstName='Jenny', lastName='Wang', emoji=':jenny:'),
	StaffMember(firstName='Jessica', lastName='Yu', emoji=':jessica:'),
	StaffMember(firstName='John', lastName='So', emoji=':john:'),
	StaffMember(firstName='John', lastName='Denero', emoji=':john:'),
	StaffMember(firstName='Joshua', lastName='Baum', emoji=':joshua:'),
	StaffMember(firstName='Julie', lastName='Ma', emoji=':julie:'),
	StaffMember(firstName='Kaavya', lastName='Shah', emoji=':kaavya:'),
	StaffMember(firstName='Kenneth', lastName='Chi', emoji=':kenneth:'),
	StaffMember(firstName='Kenny', lastName='Chi', emoji=':kenny:'),
	StaffMember(firstName='Kevin', lastName='Yang', emoji=':kevin-y:'),
	StaffMember(firstName='Kevin', lastName='Zhu', emoji=':kevin-z:'),
	StaffMember(firstName='Kevin', lastName='Li', emoji=':kevin-l:'),
	StaffMember(firstName='Khushi', lastName='Malde', emoji=':khushi:'),
	StaffMember(firstName='Kristy', lastName='Lee', emoji=':kristy:'),
	StaffMember(firstName='Laryn', lastName='Qi', emoji=':laryn:'),
	StaffMember(firstName='Lauren', lastName='Meier', emoji=':lauren:'),
	StaffMember(firstName='Linh', lastName='Tran', emoji=':linh:'),
	StaffMember(firstName='Lucy', lastName='Wan', emoji=':lucy:'),
	StaffMember(firstName='Marie', lastName='Chorpita', emoji=':marie:'),
	StaffMember(firstName='Mathilde', lastName='Mckeever', emoji=':mathilde:'),
	StaffMember(firstName='Matthew', lastName='Lee', emoji=':matthew:'),
	StaffMember(firstName='Matthew', lastName='Guo', emoji=':matthew-g:'),
	StaffMember(firstName='Megan', lastName='Zhu', emoji=':megan:'),
	StaffMember(firstName='Melanie', lastName='Cooray', emoji=':melanie:'),
	StaffMember(firstName='Melody', lastName='Sifry', emoji=':melody:'),
	StaffMember(firstName='Melvin', lastName='Aristio', emoji=':melvin:'),
	StaffMember(firstName='Michael', lastName='Lu', emoji=':michael:'),
	StaffMember(firstName='Minnie', lastName='Chen', emoji=':minnie:'),
	StaffMember(firstName='Mohsin', lastName='Sarwari', emoji=':mohsin:'),
	StaffMember(firstName='Murtaza', lastName='Ali', emoji=':murtaza:'),
	StaffMember(firstName='Nancy', lastName='Shaw', emoji=':nancy:'),
	StaffMember(firstName='Nikhita', lastName='Anumukonda', emoji=':nikhita:'),
	StaffMember(firstName='Olivia', lastName='Shiah', emoji=':olivia:'),
	StaffMember(firstName='Owen', lastName='Gong', emoji=':owen:'),
	StaffMember(firstName='Pamela', lastName='Fox', emoji=':pamela:'),
	StaffMember(firstName='Parth', lastName='Gupta', emoji=':parth:'),
	StaffMember(firstName='Patricia', lastName='Ouyang', emoji=':patricia:'),
	StaffMember(firstName='Pranad', lastName='Reddy', emoji=':pranad:'),
	StaffMember(firstName='Rachel', lastName='Dejaen', emoji=':rachel:'),
	StaffMember(firstName='Rahul', lastName='Arya', emoji=':rahul-a:'),
	StaffMember(firstName='Richard', lastName='Roggenkemper', emoji=':richard-r:'),
	StaffMember(firstName='Richard', lastName='Zhu', emoji=':richard-z:'),
	StaffMember(firstName='Rohan', lastName='Dsouza', emoji=':rohan:'),
	StaffMember(firstName='Ryan', lastName='Chao', emoji=':ryan:'),
	StaffMember(firstName='Sahil', lastName='Morchi', emoji=':sahil:'),
	StaffMember(firstName='Sameer', lastName='Saptarshi', emoji=':sameer:'),
	StaffMember(firstName='Samuel', lastName='Taplin', emoji=':samuel:'),
	StaffMember(firstName='Sarina', lastName='Sabouri', emoji=':sarina:'),
	StaffMember(firstName='Sean', lastName='Obrien', emoji=':sean-o:'),
	StaffMember(firstName='Sean', lastName='Sananikone', emoji=':sean-s:'),
	StaffMember(firstName='Selina', lastName='Wu', emoji=':selina:'),
	StaffMember(firstName='Shayna', lastName='Kothari', emoji=':shayna:'),
	StaffMember(firstName='Sherry', lastName='Fan', emoji=':sherry:'),
	StaffMember(firstName='Sophia', lastName='Xiao', emoji=':sophia:'),
	StaffMember(firstName='Sreevidya', lastName='Ganga', emoji=':sreevidya:'),
	StaffMember(firstName='Steven', lastName='Chen', emoji=':steven:'),
	StaffMember(firstName='Tim', lastName='Tu', emoji=':tim:'),
	StaffMember(firstName='Todd', lastName='Yu', emoji=':todd:'),
	StaffMember(firstName='Uma', lastName='Unni', emoji=':uma:'),
	StaffMember(firstName='Vanshaj', lastName='Singhania', emoji=':vanshaj:'),
	StaffMember(firstName='Vivian', lastName='Lu', emoji=':vivian:'),
	StaffMember(firstName='Yersultan', lastName='Sapar', emoji=':yersultan:'),
]

STAFF_EMOJI = {x.emoji for x in STAFF}
