# This action will block merges for pull requests
# where any of the files contain @blockmerge

name: "Check @blockmerge"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v0
      with:
        github-token: ${{github.token}}
        bodyDoesNotContain: "@blockmerge"
        filesChanged: 1
        linesChanged: 1
