name: "Non-Blocking Checks"
on: [pull_request]

jobs:
  nocommitCheck:
    name: "@nocommit Check"
    runs-on: ubuntu-latest
    steps:
    - name: Check for @nocommit
      uses: Cal-CS-61A-Staff/no-merge-action@releases/v0.5
      with:
        github-token: ${{github.token}}
        keyword: "@nocommit"
  pythonFormatting:
    name: "Python Formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Enforce Black Formatting
      run: |
        black . --check
  pythonUnitTests:
    name: "Python Unit Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e buildtool
        pip install pytest pytest-custom_exit_code
    - name: Test with pytest
      run: |
        pytest --suppress-no-test-exit-code
  javascriptFormatting:
    name: Javascript Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn add prettier
    - run: yarn run prettier -c "**/*.js"
