name: "Non-Blocking Checks"
on: [pull_request]

jobs:
  nocommit_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check for @nocommit
      uses: itsvs/no-merge-action@releases/v0.3
      with:
        github-token: ${{github.token}}
        keyword: "@nocommit"
  python_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black pytest-custom_exit_code
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Enforce Black Formatting
      run: |
        black . --check
    - name: Test with pytest
      run: |
        pytest --suppress-no-test-exit-code
  javascript_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn add prettier
    - run: prettier -c "**/*.js"
