# This action will block merges for pull requests
# where any of the files contain @nocommit

name: "Block @nocommit Merges"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check for @nocommit
      uses: itsvs/no-merge-action@releases/v0.1
      with:
        github-token: ${{github.token}}
        keyword: "@nocommit"
